require_relative "./hack_design/scraper"
require_relative "./hack_design/exercise"
require_relative "./hack_design/lesson"
require_relative "./hack_design/category"
require_relative "./hack_design/version"
require_relative "./hack_design/cli"